version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  redis:
    image: redis:3.2
    ports:
      -  "6379:6379"

  web:
    build: .
    command: /usr/local/heroku/bin/heroku local
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - .:/milieu/:rw
